// let date = new Date("2024-12-31T23:35z");
let date = new Date(2023,12,31,13,23,5);
let now = new Date();
// console.log(now);
// console.log(now.toString());
// console.log(now.toDateString());
// console.log(now.toLocaleDateString());
// console.log(now.toLocaleTimeString());
// console.log(now.toLocaleString());
// console.log(now.toUTCString());
// console.log(now.toISOString());
// console.log(now.toTimeString());
// console.log(now.getTime());
// Intl.DateTimeFormat().format(date);
// let year = now.getFullYear();
// console.log(year);
// console.log(now.getMonth());
// console.log(now.getDate());
// console.log(now.getDay());
// console.log(now.getHours());
// console.log(now.getMinutes());
// now.setFullYear(2003);
console.log(now>date);
console.log(now===date);
